images: configs/6961_interp.xyz
potential_params:
  potential: newtonnet
  model_path: configs/newtonnet/training_14/models/best_model.pt
path_params: 
  name: mlp
  n_embed: 2
  depth: 3
  activation: gelu
integrator_params: 
  method: dopri5
  rtol: 1.0e-6
  atol: 1.0e-8
  computation: parallel
  sample_type: uniform
  path_loss_name: integral
  # path_loss_name: growing_string
  # path_loss_params:
  #     weight_type: inv_gauss
  path_ode_names: E_pvre
optimizer_params:
  optimizer:
    name: adam
    lr: 1.0e-2
  lr_scheduler:
    name: cosine
    T_max: 1000
  # TS_time_loss_names: F_mag
  # TS_time_loss_scales: 1.0
  # TS_time_loss_scheduler:
  #   F_mag:
  #     name: cosine
  #     start_factor: 1.0
  #     end_factor: 0.0
  #     total_iters: 1000
device: cuda
num_optimizer_iterations: 1000
# n_recording_frames: 1001
# output_dir: output